# Generated by Django 6.0 on 2026-01-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='signature',
            field=models.CharField(default='Firma', max_length=100),
        ),
    ]
